// front-end/app-react/src/components/show-details/Show-details.js
 import React, { Component } from 'react'
 import axios from 'axios'
 import './Show-details.css'
 
 export default class ShowDetails extends Component {
     state = {
         id: '',
         name: '',
         price: 0,
         quantity: 0
     }
     async componentDidMount(){
         if ( this.props.match.params.id) {
             const res = await axios.get(`http://localhost:8080/api/products/${this.props.match.params.id}` )
             console.log(res.data);
             this.setState({
                 name: res.data.stockOneProduct.name,
                 price: res.data.stockOneProduct.price,
                 quantity: res.data.stockOneProduct.quantity
             })
             
         }
     }
     render() {
         if(!localStorage.getItem('reaCurrentUser')){
             window.location.href = '/' 
             return
         }
         return (
             <div>
                 <div className="container">
                     <div className="columns is-mobile is-centered">
                         <div className="column is-10">
                             <div className="columns main-div">
                                 <div className="column">
                                     <div class="card">
                                         <div class="is-size-4 is-vcentered">
                                             <h5 class="is-size-5"><b>{this.state.name.slice(0,1).toUpperCase() + this.state.name.slice(1, -4)}</b> </h5>
                                         </div>
                                         <div class="cadr-image">
                                             <figure class='image is-4by3'>
                                                 <img src={'/img/' + this.state.name} alt=""/>
                                             </figure>
                                         </div>
                                         <div class="card-footer">
                                             <a href="/products" class="button is-info">Atrás</a>
                                         </div>
                                     </div>     
                                 </div>
                                 <div className="column">
                                     <p className="bd-notification is-primary">
                                         <code className="html"><b>Precio:{this.state.price} </b> </code> <br/>
                                     </p>
                                     <p className="bd-notification is-primary">
                                         <code className="html"><b>Unidades disponibles:{this.state.quantity}</b> </code><br/>
                                     </p>  
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>                 
             </div>
         )
     }
 }

// front-end/app-angular/src/app/components/show-details/show-details.component.ts
 import { Component, OnInit } from '@angular/core';
 import { ActivatedRoute, Params  } from '@angular/router';
 import { HttpProductsService } from '../../services/http-products.service';

 @Component({
     selector: 'app-show-details',
     templateUrl: './show-details.component.html',
     styleUrls: ['./show-details.component.css']
 })
 export class ShowDetailsComponent implements OnInit {
     id: string;
     product: {
         name: string,
         price: number,
         quantity: number
     };
     constructor(
         private httpProductsService: HttpProductsService,
         private activatedRoute: ActivatedRoute
     ){
         this.id = this.activatedRoute.snapshot.params.id;
     }

  ngOnInit(): any{
     this.httpProductsService.getOneProduct(this.id).subscribe((data: any) => {
         this.product = data.stockOneProduct;
         console.log('DETALLES:...', this.product);
     });
  }
 }

 <div class="container">
     <div class="columns is-mobile is-centered">
         <div class="column is-10">
             <div class="columns main-column">
                 <div class="column">
                     <div>
                         <div class="card">
                             <div class="is-size-4 is-vcentered">
                                 <h5 class="is-size-5"><b>{{ product.name.slice(0,-4) | titlecase}}</b> </h5>
                             </div>
                             <div class="cadr-image">
                                 <figure class='image is-4by3'>
                                     <img [src]='"/assets/img/" + product.name' alt="" class='mt-2 mage is-4by3'>
                                 </figure>
                             </div>
                             <div class="card-footer">
                                 <a href="products" class="button is-info">Atrás</a>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="column">
                     <p class="bd-notification is-primary">
                         <code class="html"><b>Precio: </b>{{product.price | currency:'$'}}</code><br>
                     </p>
                     <p class="bd-notification is-primary">
                         <code class="html"><b>Unidades disponibles:</b> {{product.quantity}}</code><br>
                     </p>
                 </div>
             </div>
         </div>
     </div>
</div>
