// front-end/app-angular/src/app/components/dashboard-products/dashboard-products.component.ts
 import { Component, OnInit, OnDestroy } from '@angular/core';
 import { HttpProductsService } from '../../services/http-products.service';
 import { CartService } from '../../services/cart.service';
 import { Router } from '@angular/router';
 import swal from 'sweetalert';

 @Component({
     selector: 'app-dashboard-products',
     templateUrl: './dashboard-products.component.html',
     styleUrls: ['./dashboard-products.component.css']
 })
 export class DashboardProductsComponent implements  OnInit, OnDestroy {
     idCurrentUser: string;
     idProduct: number;
     quantity: number;
     price: number;
     name: string;
     productFound: false;

     constructor(
         private httpProductsService: HttpProductsService,
         private cartService: CartService,
         public router: Router) { }
         setFilter = '';
         products  = [];
         numRecords = 0;

     ngOnInit(): void {
         this.httpProductsService.getProducts().subscribe((data: any) => {
             const results = data.stockProducts;
             for (const product of results) {
                 this.products.push(product);
             }
             console.log('Todos los productos: ', this.products);
             this.numRecordsInCart();
         });

     }
     sendToCart(id, howMany: any, price, name, quantity): void{
         this.idCurrentUser = localStorage.getItem('angCurrentUser');
         this.idProduct = id;
         this.quantity = howMany;
         this.price = price;
         this.name = name;
         const product = {
             fk_id_user: Number(this.idCurrentUser),
             fk_id_product: this.idProduct,
             quantity: Number(this.quantity),
             price: Number(this.price)
         };
         if (howMany > quantity){
             swal('Existencias insuficientes', `No existe suficiente cantidad de ${this.name.toUpperCase()} para esta venta`, 'error' )
             return;
          }
         if (howMany < 0 ){
             swal('Valores negativos', `No se permiten valores negativos para ${this.name.toUpperCase()} para esta venta`, 'error' )
             return;
         }
         this.httpProductsService.sendToCart(product).subscribe((res: any) => {
             this.productFound = res.productFound;
             if (this.productFound){
                 swal('Producto duplicado', `${this.name.toUpperCase()}, ya existe en el carrito de compras`, 'error');
             }
             this.numRecordsInCart();
             console.log(res);
         });
     }
     numRecordsInCart(): any {
         const user = {id: localStorage.getItem('angCurrentUser')};
         this.cartService.numRecordsInCart(user).subscribe((res: any) => {
               this.numRecords = res.num[0].RECORDS_IN_CART;
         });
     }

     ngOnDestroy(): void {
         console.log('Bye');
     }
 }

 <app-nav-bar [numRecordsInCart] = this.numRecords ></app-nav-bar>
 <div class="container main-div">
     <header>
         <div class="columns">
             <div class="column">
                 <h3 class='is-size-4 is-vcentered'>Catálogo de productos</h3>
             </div>
             <div class="column is-4 ml-5">
                ¿Que estás buscando?
                 <div class="control">
                     <input
                         class="input is-primary"
                         type="text"
                         name="setFilter"
                         placeholder="Buscar producto"
                         [(ngModel)] = "setFilter"
                         autofocus
                     >
                 </div>
             </div>
         </div>
         <hr class = 'is-centered'/>
     </header>
     <div class="scroll">
         <div class="columns is-mobile is-centered is-multiline is-one-quarter mt-2">
             <div class = '' *ngFor="let p of products | filter: setFilter">
                 <div class="card is-mobile column is-one-quarter mr-1 ml-1" style="width: 17rem; height: 28rem;">
                    <div className="card-image">
                        <figure className="image is-48x48">
                             <img [src]='"/assets/img/" + p.name'>
                        </figure>
                    </div>
                    <div class="card-content">
                         <div class="media">
                             <div class = 'media-content'>
                                 <p class="title is-4">{{ p.name.slice(0,-4) | titlecase}}</p>
                             </div>
                         </div>
                         <div class="content">
                             <p class="subtitle is-6"><b>Precio:</b>{{p.price | currency:'$'}}</p>
                             <p class="subtitle is-6"><b>Udes. disponibles:</b> {{p.quantity}}</p>
                             <div class="buttons is-narrow">
                                 <a
                                     [routerLink]="['show-details', p.id]"
                                     class="button is-small is-info"
                                     style="width: 4rem">
                                         Detalles
                                 </a>
                                 <button
                                     class = "button is-small is-warning "
                                     (click) = "sendToCart(p.id, howMany.value, p.price, p.name.slice(0,-4), p.quantity)"
                                     style="width: 4rem" >
                                         Añadir
                                 </button>
                                 <div class="control  is-5">
                                     <input
                                         class="input is-small is-primary"
                                         style='width: 50px'
                                         type="number"
                                         value = "1"
                                         style="width: 50px"
                                         #howMany
                                     >
                                </div>
                             </div>
                         </div>
                    </div>
                 </div>
             </div>
         </div>
     </div>
 </div>

// front-end/app-react/src/components/dashboard-products/Dashboard-products.js
 import React, { Component } from 'react'
 import Navigation from '../nav-bar/Nav-bar'
 import axios from 'axios'
 import './Dashboard-products.css'
 import { Link } from 'react-router-dom'
 import swal from 'sweetalert';
 
 export default class DashboardProducts extends Component {
     constructor(props){
         super(props);
         this.state = {
             products: [],
             textToSearch: '',
             quantityToSell: 1,
             numRecords: 0
         }
         this.updateSearch = this.updateSearch.bind(this);
         this.handleChange = this.handleChange.bind(this);
     }

 //----------------------------------------------------------------------------------------------
   componentDidMount(){
         this.getProducts();
         this.numRecordsInCart();
   }
 //----------------------------------------------------------------------------------------------
  getProducts(){ 
    axios.get(`http://localhost:8080/api/products`)
     .then(res => {
         this.setState({ products: res.data.stockProducts });
         console.log('Todos los productos:...', res.data.stockProducts);
     })
  }
  sendToCart(p){
     if ( this.state.quantityToSell > p.quantity){
         swal('Existencias insuficientes', `No existe suficiente cantidad de ${p.name.slice(0,1).toUpperCase() + p.name.slice(1, -4)} para esta venta`, 'error' )
         return
     }
     if ( this.state.quantityToSell < 0 ){
         swal('Valores negativos', `No se permiten valores negativos para ${p.name.slice(0,1).toUpperCase() + p.name.slice(1, -4)}`, 'error' )
         return
     }
     this.idCurrentUser = localStorage.getItem('reaCurrentUser');
     const product = {
         fk_id_user: Number(this.idCurrentUser),
         fk_id_product: p.id,
         quantity: this.state.quantityToSell,
         price: Number(p.price)
     }
     axios.post(`http://localhost:8080/api/cart/`, product)
     .then(res => {
         if (res.data.productFound){
             swal('Producto duplicado', `${p.name.slice(0,1).toUpperCase() + p.name.slice(1, -4)}, ya existe en el carrito de compras`, 'error');
         }
         this.numRecordsInCart();
     })
  }
 //----------------------------------------------------------------------------------------------
 numRecordsInCart(){
     const user = {id: localStorage.getItem('reaCurrentUser')};
     axios.put(`http://localhost:8080/api/cart/`, user)
         .then( res => {
             this.setState({numRecords: res.data.num[0].RECORDS_IN_CART})
         })
 }
  updateSearch (e){
     this.setState({
         textToSearch: e.target.value
     })
 }
 //----------------------------------------------------------------------------------------------
  handleChange(event) { //Controla los cambios del input de cantidad
     this.setState({quantityToSell: event.target.value});
  }
 //----------------------------------------------------------------------------------------------
     render() {
        
         if(!localStorage.getItem('reaCurrentUser')){
             window.location.href = '/' 
             return
         }
         let filteredProducts = this.state.products.filter(
             (product) => {
                 return product.name.toLowerCase().indexOf(this.state.textToSearch.toLowerCase()) !== -1
             }
         )
         return (
             <div>
                 <Navigation counter = {this.state.numRecords}/>
                 <div className="container main-div " >
                     <header>
                         <div className="columns ">
                             <div className="column">
                                 <h3 className='is-size-4 is-vcentered'>Catálogo de productos</h3>
                             </div>
                             <div className="column is-4 ml-5">
                                 ¿Que estás buscando?
                                 <div className="control">
                                     <input 
                                         type="text" 
                                         className="input is-primary"
                                         placeholder="Buscar producto" 
                                         value={this.state.textToSearch}
                                         onChange={this.updateSearch.bind(this)}
                                         autoFocus
                                     />                                        
                                 </div>
                             </div>
                         </div>
                         <hr className = 'is-centered'/>
                     </header>
                     <div className='scroll'>
                         <div className ='columns is-multiline is-mobile is-centered'>{
                             filteredProducts.map(p =>(
                                 <div className ="columns test mt-2" key={p.id}>
                                     <div className="card is-mobile column is-one-quarter px-3 py-3" style={{width: '18rem', height: '28rem'}}>
                                         <div className="card-image">
                                             <figure className="image is-4by3">
                                                 <img src={'/img/' + p.name} alt=""/>
                                             </figure>
                                         </div>
                                         <div className="card-content">
                                             <div className="media">
                                                 <div className="media-content">                                                     
                                                     <p className="title is-4">{p.name.slice(0,1).toUpperCase() + p.name.slice(1, -4)}</p>
                                                 </div>
                                             </div>
                                             <div className="content">
                                                 <p className="subtitle is-6"><b>Precio:</b> {p.price}</p>
                                                 <p className="subtitle is-6"><b>Udes. disponibles:</b> {p.quantity}</p> 
                                                 <div className="buttons is-narrow">
                                                     <Link 
                                                         className="button is-info is-small"
                                                         to={"/edit/" + p.id}
                                                         style={{width: '4rem'}}>
                                                             Detalles
                                                     </Link>
                                                     <button 
                                                         className="button is-warning is-small" 
                                                         onClick={() => this.sendToCart(p)}
                                                         style={{width: '4rem'}}>
                                                             Agregar
                                                     </button>
                                                     <div className="control is-5">
                                                         <input 
                                                             className="input is-primary is-small"
                                                             type="number"
                                                             min="0"
                                                             max={p.quantity} 
                                                             disabled={ (p.quantity <= 0 ) ? true : false } 
                                                             style={{'width': '50px'}}
                                                             onChange={this.handleChange}
                                                             defaultValue="1"                                                  
                                                         />
                                                     </div> 
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                             ))
                         }
                         </div>
                     </div>                     
                 </div>
             </div>
         )
     }
 }
