// front-end/app-react/src/components/nav-bar/Nav-bar.js
 import React, { Component } from 'react'
 import { Link } from 'react-router-dom'
 import '../nav-bar/Nav-bar.css'
 
 export default class Navbar extends Component {
     logout(){
         localStorage.removeItem('reaToken')
         localStorage.removeItem('reaCurrentUser')
     }
     render() {
         return (
             <nav className="navbar container" role="navigation" aria-label="main navigation">
                 <div className="navbar-brand is-size-5">
                     <h3>La bodega</h3>
                 </div>
                 <div id="navbarBasicExample" className="navbar-menu">
                     <div className="navbar-end">
                         <div className="nav-link">
                             <Link
                                 className="is-light"
                                 to="/Products">
                                 <i className="fa fa-th"></i>
                             </Link>
                             <Link
                                 className="is-light"
                                 to="/ShowCart"
                                 >
                                 <i className="fa fa-shopping-cart">
                                     <span className="tag is-danger">{this.props.counter ? this.props.counter: ''}</span>
                                 </i>
                             </Link>
                             <Link className="is-light" to="/Products">
                                 <i className="fa fa-credit-card"></i>
                             </Link>
                             <Link className="is-light" 
                                 to="/" >
                                 <i 
                                     className="fa fa-sign-out"
                                     onClick={this.logout}>  
                                 </i>
                             </Link>
                         </div>
                     </div>
                 </div>
             </nav>
         )
     }
 }

// front-end/app-angular/src/app/components/nav-bar/nav-bar.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router, CanActivate } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';


@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
  @Input() numRecordsInCart: number;

  currentId = localStorage.getItem('angCurrentUser');

  constructor(
      public router: Router,
      public authService: AuthService,
      public cartService: CartService) { }

  ngOnInit(): void {

  }

  showcart(): void {
     this.router.navigate(['/showcart']);
 }

}

<nav class="navbar container " role="navigation" aria-label="main navigation">
     <div class="navbar-brand">
         <a href="">
             <a class="navbar-brand is-size-4" href="#"> La bodega</a>
         </a>
     </div>
     <div id="navbarBasicExample" class="navbar-menu">
         <div class="navbar-end">
             <div class="nav-link">
                 <a
                     class="is-light"
                     href="products">
                     <i class="fas fa-th"></i>
                 </a>
                 <a
                     class="is-light"
                     (click)="showcart()">

                     <i class="fas fa-shopping-cart">
                       <span class="tag is-danger">{{numRecordsInCart}}</span>
                     </i>
                 </a>
                 <a class="is-light">
                     <i class="fas fa-credit-card"></i>
                 </a>
                 <a class="is-light" (click)="this.authService.logout()">
                     <i class="fas fa-sign-out-alt"></i>
                 </a>
             </div>
         </div>
     </div>
 </nav>
