// front-end/app-angular/src/app/components/auth/login/login.component.ts
 import { Component, OnInit } from '@angular/core';
 import { AuthService } from '../../../services/auth.service';
 import { CartService } from '../../../services/cart.service';
 import { Router } from '@angular/router';
 import { NgForm, FormGroup, FormControl, FormBuilder, Validators } from '@angular/forms';

 @Component({
     selector: 'app-login',
     templateUrl: './login.component.html',
     styleUrls: ['./login.component.css']
 })
 export class LoginComponent implements OnInit {
     loginForm: FormGroup;
     logError: boolean;
     email: string;
     password: string;


 constructor(public authService: AuthService,
             public cartService: CartService, private builder: FormBuilder, public router: Router) {
     this.loginForm = this.builder.group({
         email: [null, Validators.compose([Validators.email, Validators.required])],
         password: [null, Validators.required]
     });
 }

 ngOnInit(): void {

 }
 login(form: FormGroup): void {
     this.email = form.value.email;
     this.password = form.value.password;
     if (this.email !== null && this.password !== null) {
         const user = {email: this.email, password: this.password};
         this.authService.login(user).subscribe((res: any) => {
         console.log('DATOS DEVUELTOS DEL SERVER:...', res);
         if (res.token){
             localStorage.setItem('angToken', res.token);
             localStorage.setItem('angCurrentUser', res.currentUser.id);
             this.numRecordsInCart();
             this.router.navigate(['products']);
         } else{ // Error al validar el usuario y password
             this.logError = true;
         }
      });
     }
  }
  numRecordsInCart(): any {
      const user = {id: localStorage.getItem('angCurrentUser')};
      this.cartService.numRecordsInCart(user).subscribe((res: any) => {
          console.log('Número de registros en el carrito...:', res.num[0].RECORDS_IN_CART);
      });
  }
}

 <div class="main-div">
     <div class="columns is-mobile container is-8">
         <div class="column is-half is-offset-one-quarter">
             <label class="label is-size-4 columns is-centered has-text-white">Inicia sesión</label>
             <form
                 [formGroup]="loginForm"
                 (ngSubmit)="login(loginForm)"
                 novalidate>
                 <h6
                     class="is-size-5 has-text-white"
                     *ngIf="logError">Error en nombre de usuario y/o conraseña
                 </h6>
                 <div class="field">
                     <label class="label has-text-white">Correo electrónico</label>
                     <div class="control has-icons-left has-icons-right">
                         <input
                             type="email"
                             class="input is-success"
                             formControlName="email"
                             placeholder="E-mail"
                             autofocus
                         >
                         <span class="icon is-small is-left">
                             <i class="fas fa-user"></i>
                         </span>
                         <span class="icon is-small is-right">
                             <i class="fas fa-check"></i>
                         </span>
                     </div>
                     <!-- <p class="help is-size-5 is-danger">This username is available</p> -->
                 </div>
                 <h6 class="help is-size-5 has-text-white" *ngIf="!loginForm.controls['email'].valid && loginForm.controls['email']?.touched">Email es requerido o no tiene formato vállido</h6>
                 <div class="field">
                     <label class="label has-text-white">Contraseña</label>
                     <div class="control has-icons-left has-icons-right">
                         <input
                             type="password"
                             class="input is-success"
                             formControlName="password"
                             placeholder="Password"
                             required
                         >
                         <span class="icon is-small is-left">
                             <i class="fa fa-key"></i>
                         </span>
                         <span class="icon is-small is-right">
                             <i class="fas fa-check"></i>
                         </span>
                     </div>
                     <!-- <p class="help is-size-5 is-danger">This username is available</p> -->
                 </div>
                 <h6 class="is-size-5 has-text-white" *ngIf="loginForm.get('password').hasError('required') && loginForm.get('password').touched">Password is requerido</h6>
                 <div class="field is-grouped columns is-centered mt-1">
                     <div class="control">
                         <button type = 'submit' class="button is-success">Ingresar</button>
                     </div>
                 </div>
             </form>
         </div>
     </div>
</div>

// front-end/app-react/src/components/auth/login/Login.js
 import React, { Component } from 'react'
 import './Login.css'
 import axios from 'axios'
 
 
 export default class Login extends Component {
     constructor (props){
         super (props)
         this.state = {
             userName: '',             
             password: '',
             logErrors: [],   
             loginSucces: true
             
         }
         this.handleChangeUserName = this.handleChangeUserName.bind(this)
     }
     //------------------------------------------------------------------
     handleChangeUserName(e) { //Controla los cambios del input donde se escribe el email         
         this.setState({userName: e.target.value});
         this.setState({ [e.target.name]: e.target.value }); 
     }
     //------------------------------------------------------------------
     handleOnChangePassword = (e) => {
         this.setState({password: e.target.value });
         this.setState({ [e.target.name]: e.target.value });
     }
     //------------------------------------------------------------------
     validate = () => {
         
         let tempErrors = this.state.logErrors
         let formIsValid = true
         if (this.state.userName.length === 0){
             formIsValid = false
             tempErrors['email'] = 'Correo electrónico es requerido'
         }else{
             if(this.state.userName !== "undefined") {
                 let lastAtPos = this.state.userName.lastIndexOf('@')
                 let lastDotPos = this.state.userName.lastIndexOf('.')
                 if (!(lastAtPos < lastDotPos && lastAtPos > 0 && this.state.userName.indexOf('@@') === -1 && lastDotPos > 2 && (this.state.userName.length - lastDotPos) > 2)) {
                     formIsValid = false;
                     tempErrors["email"] = "Email no es válido";
                 }
             }
         }
         if (this.state.password.length === 0){
             formIsValid = false
             tempErrors['password'] = 'Password es requerido'
         }
         this.setState({logErrors: tempErrors})
         console.log(this.state.logErrors)
         return formIsValid;   
     }
     onSubmit = async e => {         
         e.preventDefault()
         if(this.validate()) {
             const user = {
                 email: this.state.userName,
                 password: this.state.password
             }
             axios.post(`http://localhost:8080/api/users/`, user)
             .then(res => {
                 console.log(res)
                 if (res.data.message === 'Usuario no existe...'){
                     this.setState({loginSucces: false})
                 }else{
                     this.setState({loginSucces: true})
                     localStorage.setItem('reaToken', res.data.token)
                     localStorage.setItem('reaCurrentUser', res.data.currentUser.id)
                     this.numRecordsInCart()
                     window.location.href = '/Products'
                 }
             })
         }else{
             console.log('Errores de validación...');
         }
     }

     //------------------------------------------------------------------
     numRecordsInCart(){
         const user = {id: localStorage.getItem('reaCurrentUser')};
         axios.put(`http://localhost:8080/api/cart/`, user)
             .then( res => {
                 console.log('Número de registros en el carrito...:', res.data.num[0].RECORDS_IN_CART);                                                                      
             })
     }
     //------------------------------------------------------------------
     render() {
         const isLoggedIn = this.state.loginSucces
         return (
             <div>
                 <div className="main-login">
                     <div className="columns is-mobile container is-8">
                         <div className="column is-half is-offset-one-quarter">
                             <label className="label has-text-white is-size-4 columns is-centered">Inicia sesión</label>
                             { !isLoggedIn ? 
                                 <h6 className="has-text-white"> <b>Error en nombre de usuario y/o contraseña</b> </h6>
                                 : 
                                 <p></p>
                             }                             
                             <form
                                 onSubmit={this.onSubmit}
                                 noValidate
                             >
                                 <div className="field">
                                     <label className="label has-text-white is-left" align="left">Correo electrónico</label>
                                     <div className="control has-icons-left has-icons-right">
                                         <input 
                                             value={this.state.userName}
                                             name="userName"                                             
                                             type="email"
                                             className="input is-success"
                                             id="defaultFormRegisterEmailEx2"
                                             placeholder="E-mail"
                                             autoFocus
                                             required
                                             onChange={this.handleChangeUserName}
        
                                         />
                                         <span className="icon is-small is-left">
                                             <i className="fa fa-user"></i>
                                         </span>
                                         <span className="icon is-small is-right">
                                             <i className="fa fa-check"></i>
                                         </span>                                         
                                     </div>
                                     <span className = 'help has-text-white' align="left">{this.state.logErrors['email']}</span>
                                 </div>
                                 <div className="field">
                                     <label className="label has-text-white is-left" align="left">Contraseña</label>
                                     <div className="control has-icons-left has-icons-right">
                                         <input 
                                             value={this.state.password}
                                             type="password"
                                             className="input is-success"
                                             placeholder="Password"
                                             required
                                             onChange={this.handleOnChangePassword}                                             
                                         />
                                         <span className="icon is-small is-left">
                                             <i className="fa fa-key"></i>
                                         </span>
                                         <span className="icon is-small is-right">
                                             <i className="fa fa-check"></i>
                                         </span>                                         
                                     </div>
                                 </div>
                                 <span className = 'help has-text-white' align="left">{this.state.logErrors['password']}</span>
                                 <div className="field is-grouped columns is-centered test">
                                     <div 
                                         className="control">
                                             <button 
                                                 type = 'submit' 
                                                 onClick={() => this.onSubmit}
                                                 className="button is-success">
                                                     Ingresar
                                                 </button>
                                     </div>
                                 </div>
                             </form>
                         </div>

                     </div>
                 </div>
             </div>
         )
     }
 }
